name: Build & Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      # Tu URL de BD en Railway o el secreto que uses
      DEV_DATABASE_URL: ${{ secrets.MYSQL_CONN }}
    steps:
      # 1. Chequear el código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Preparar Node (si necesitas ejecutar npm install/test antes del build)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Crear .env con la URL de base de datos
      - name: Create .env file
        run: echo "DEV_DATABASE_URL=${DEV_DATABASE_URL}" > .env

      # 4. Instalar dependencias y (opcional) ejecutar tests o migraciones
      - name: Install dependencies
        run: npm ci

      # - name: Run migrations
      #   run: npx sequelize-cli db:migrate --env production

      # - name: Run tests
      #   run: npm test

      # 5. Loguearse en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build y push de la imagen
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/mysql-restapi:${{ github.sha }}
            ${{ secrets.DOCKER_USER }}/mysql-restapi:latest
